### ISSUE TITLE
Global nav only appears on main site of network

### ISSUE THREAD

**Issue by jedifunk** [rrennick/network-wide-menu#1]
This plugin is exactly what I need, but after updating to WP 3.5 it has stopped functioning.  The global nav only shows on the main site.

What's interesting is that it seems to partially work, in that it loads the appropriate HTML for the UL & LIs, as well as adding <a> tags, but it does NOT populate the <a> with a URL.

You can see the issue at secureinvestorsdemo.com

**Comment by rrennick** [comment]
Which version of the plugin are you using?

**Comment by jedifunk** [comment]
I just added the latest I believe. It says, 0.1 inside the plugin

**Comment by rrennick** [comment]
Try putting the original plugin back.

**Comment by jedifunk** [comment]
what would be the original? the one from 2011? what changed between that and the one here on GitHub?

edit: ok, doing so made no difference

**Comment by rrennick** [comment]
I thought that was worth checking. I looked at the link you provided and as far as I can tell, the menus are populated correctly.

**Comment by jedifunk** [comment]
yes, the menu populates just fine on the main site, but on the other 4 sites, it doesn't appear.  also to be clear, i'm speaking of the investments, home mortgage, tax, etc links.

**Comment by rrennick** [comment]
Do you mind posting a link to a site where it's not working?

**Comment by jedifunk** [comment]
sure... http://investments.secureinvestorsdemo.com/

I have also tried, creating a new menu and using it, but that didn't work either.

**Comment by rrennick** [comment]
I'll see if I can reproduce sometime in the next week.

**Comment by jedifunk** [comment]
not sure if this makes a difference with the plugin, but i noticed this in the codex today on the wp_nav_menu page... Note: As of 3.5, if there are no menu items, no HTML markup will be output.

which seems to be exactly what is happening

**Comment by rrennick** [comment]
The network menu does its thing by replacing the menu items. It doesn't replace the menu items when the source menu is empty (of items).

**Comment by jedifunk** [comment]
i understand this... the source menu (from the main site) appears just fine. its all the subsites that don't load the menu

**Comment by rrennick** [comment]
It is working fine for me in 3.5.1. Have you turned off all plugins on a test subsite with TwentyTwelve as the theme?

**Comment by jedifunk** [comment]
oddly, twentytwelve doesn't show up as a theme option for the subsites... it does for the main site though.

i'm wondering if it might be the way the menus get registered? there are 2 menus on each site. the Global (using your plugin) and a primary.

a little back info might help too... 5 sites, 1 parent theme that is on the main site, 4 child themes (one for each of the subsites), one functions.php file for all the sites that is in the parent theme. this is how it is in the functions.php in the parent theme loads the menus.

register_nav_menus( array(
        'global' => __( 'Global Menu', 'secure' ),
        'primary' => __( 'Primary Menu', 'secure' ),
    ) );

should i be using your method as shown in the blog post at http://wpmututorials.com/plugins/add-a-global-menu-to-your-network/

**Comment by rrennick** [comment]
**oddly, twentytwelve doesn't show up as a theme option for the subsites... it does for the main site though.**

Go to network admin -> themes and enable TwentyTwelve

**Comment by jedifunk** [comment]
it is network enabled already

**Comment by rrennick** [comment]
This is a ticket system for reporting bugs/issues vs being general support. Use stackexchange or the wordpress.org support forums to sort out the issue with your network themes.

If you can reproduce the issue with TwentyTen, TwentyEleven or TwentyTwelve on a site with no plugins active, post the info here.

**Comment by jedifunk** [comment]
thanks for being unhelpful... i wasn't ever asking you to sort out my theme issue... just the fact that after upgrading core, your plugin stopped working.

**Comment by rrennick** [comment]
I apologize if I offended you. I don't know whether other github developers provide support through the issue tracking system. It's fine if they choose to do that. However, support isn't what issue/bug tracking systems are typically used for.

In my situation, I also use github for my day job which means that all notices from github are sent to my work email. Dropping my work to do volunteer support for my hobby/volunteer community contributions isn't fair to my employer.

**Comment by jedifunk** [comment]
Ron - fair enough... i appreciate your efforts to this point. I will let you know if I determine anything further with regard to the plugin.

thanks again
